on:
  push:
    branches:
      - 'main'
    paths:
      - 'theme-dark-arc.css'
  workflow_dispatch:

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: auto minify the files
        uses: nizarmah/auto-minify@v3
        with:
          overwrite: false
          maxdepth: 1

      - name: auto commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: Minify theme"
          file_pattern: '*.min.css'
          branch: ${{ github.ref }}
